#!/usr/bin/env python

import os
import boto3

def recursive_s3_delete(bucket_name, prefix):

    s3 = boto3.resource('s3')
    bucket = s3.Bucket(bucket_name)

    # Delete objects within the specified prefix
    objects_to_delete = bucket.objects.filter(Prefix=prefix)

    [ print(f'delete s3://{bucket_name}/{obj.key}') for obj in objects_to_delete ]

    bucket.delete_objects(
        Delete={
            'Objects': [{'Key': obj.key} for obj in objects_to_delete]
        }
    )

    # Delete objects in subdirectories recursively
    for obj in bucket.objects.filter(Prefix=prefix):
        obj.delete()

if __name__ == '__main__':

    bucket_name = os.environ["S3_BUCKET_NAME"]
    bucket_prefix = os.environ["S3_BUCKET_PREFIX"]

    recursive_s3_delete(bucket_name,
                        prefix=bucket_prefix)